version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install Terraform"
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin
      - terraform -version

  pre_build:
    commands:
      - echo "Preparing lambda package"
      # Zip the contents of the lambda directory, not the directory itself.
      - zip -j lambda/daily_bible_emailer.zip lambda/*
      - echo "Changing to dev environment directory"
      - cd envs/dev/us-east-1
      - echo "Terraform init"
      # Provide backend configuration directly instead of using a backend.hcl file.
      # This avoids having to commit the backend.hcl file to the repository.
      # IMPORTANT: Replace the bucket and dynamodb_table names if you used different ones during bootstrap.
      - terraform init -input=false -backend-config="bucket=terraform-backend-960258040170" -backend-config="key=daily_bible_emailer/dev/us-east-1/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="terraform-state"

  build:
    commands:
      - echo "Terraform validate"
      # No need for `|| true` as a failed validation should stop the build
      - terraform validate
      - echo "Terraform apply"
      - terraform apply -auto-approve -input=false -var="artifact_bucket_name=${ARTIFACT_BUCKET}"

artifacts:
  files: []
